name: Sync envs

on:
  schedule:
    - cron: '0 6 * * 1-5'
  workflow_dispatch:

jobs:
  sync-dev:
    name: Sync dev
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6.0.0

      - uses: connor-baer/action-sync-branch@066ffc273774493f6327c8f373ef14228961af9c # v2.0.1
        with:
          branch: dev
          token: ${{ secrets.GH_ACTIONS_PAT }}
          force: true

  sync-stage:
    name: Sync stage
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6.0.0

      - uses: connor-baer/action-sync-branch@066ffc273774493f6327c8f373ef14228961af9c # v2.0.1
        with:
          branch: stage
          token: ${{ secrets.GH_ACTIONS_PAT }}
          force: true
